"""FULL SLATE - Sat 2026-09-26 (Week 4). FBS + FCS.
Every market/model/weather/injury value below was RETRIEVED via web search on 2026-09-26
(sources listed in the workbook). sp = HOME spread (negative = home favored).
fpi_h = ESPN FPI win probability for the HOME team. sp_h/sp_a = Bill Connelly SP+ projected score.
Nothing here is estimated. Where a field is absent it was not retrievable."""

G = [
# ------------------------------------------------------------------ FBS
dict(id=1, div="FBS", et="12:00", a="Texas", h="Tennessee", sp=5.5, tot=55.5, mlh=176, mla=-218, to=-112, tu=-108,
  fpi_h=0.300, sp_h=28, sp_a=29, wx="Sunny, 77F, light NE breeze, no rain", wxc="clear",
  rec="TEX 3-0 (#1), TENN 3-0 (#14)", line="Opened TEX -3.5; -4.5 this morning; now -5.5 at CBS/consensus - money still coming on Texas",
  ana="Market has Texas by 4.5 after steady money through two numbers. The models split hard: FPI makes Texas 70% (about an 8.6-pt favourite) while SP+ projects 29-28, essentially a pick'em. With one model on each side of the number there is no directional read. Weather is ideal.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="A second model landing on the same side as FPI or SP+"),
dict(id=2, div="FBS", et="12:00", a="Illinois", h="Ohio State", sp=-27.5, tot=54.5, mlh=-4348,
  fpi_h=0.953, sp_h=37, sp_a=16, wx="Mostly sunny, 73F, N 5-10", wxc="clear",
  rec="ILL FPI #44", ana="FPI (95.3%) agrees with the 27.5 exactly; SP+ has Ohio State by 21, 6.5 short of the number. Split models on a massive spread. Big favourites empty the bench late, which is the only structural angle.",
  bet="No side. Structural: Ohio State 2H under / team-total under", btype="Structural", stake="0.5", conf="Low",
  kill="Ohio State keeping starters in past the third quarter"),
dict(id=3, div="FBS", et="12:00", a="Colorado", h="Baylor", sp=-9.5, tot=55.5, mlh=-375, mla=290,
  fpi_h=0.803, other="SportsLine computer model likes Colorado", wx="not retrieved (Waco)", wxc="unknown",
  inj="BAY QB DJ Lagway PROBABLE (ankle; 'green light' per Aranda). Was 60-70% last week.",
  line="Books split -9.5 / -10", ana="FPI (80.3%) is more bullish on Baylor than the market; SportsLine likes Colorado. Lagway is cleared but his ankle is the swing factor, and the -9.5/-10 split is the market hedging it. Take the number, not a side.",
  bet="Shop only: Colorado at +10, or Baylor at -9.5", btype="Shop", stake="0.5", conf="Low",
  kill="Lagway limited early - Baylor offence without him is a different team"),
dict(id=4, div="FBS", et="12:00", a="Wake Forest", h="Louisville", sp=-13.5, tot=57.5, mlh=-550, mla=385,
  spwp_h=0.78, other="SP+ ratings: LOU 13.3 (25th), WAKE 3.6 (63rd); SP+ LOU 78%",
  line="Alt -13", ana="SP+ ratings differ by 9.7 points; plus home field that is a Louisville win by ~12.7, within a point of the market. The model agrees with the price. Only value is the half-point at -13.",
  bet="No bet (lay -13 not -13.5 if you must)", btype="None", stake="0", conf="Low", kill="-"),
dict(id=5, div="FBS", et="12:00", a="Virginia Tech", h="Boston College", sp=14.5, tot=47.5, mla=-670,
  fpi_h=0.136, sp_h=19, sp_a=34, wxc="storm_core",
  wx="NOR'EASTER: NWS rain through the entire game window; NE sustained 18-35 mph, gusts 40+; 57F; rain building through 2H",
  rec="VT 3-0; BC 2-1 (beat FCS Maine only 22-16)", line="Totals 47.5 / 48.5 / 49.5 across books - some have moved for weather, some have not",
  ana="SP+ projects 34-19 (53 total) and FPI 86.4% - both agree with VT -14.5 on the side. But SP+ is a neutral-weather number and this game is played inside a Nor'easter: sustained winds well above the ~15-20 mph threshold where passing and kicking collapse, rain start to finish. Books are split 47.5-49.5, meaning the adjustment is incomplete. The under is only a bet at the highest number available.",
  bet="UNDER 49.5 (shop; pass at 47.5)", btype="Weather+Shop", stake="1", conf="Medium",
  kill="Storm track shifting east before noon, or 49.5 no longer available", evcalc=dict(side="under", line=49.5, price=-110, base=53.0, adj=(-3,-6,-9))),
dict(id=6, div="FBS", et="12:00", a="Sam Houston", h="Texas Tech", sp=-34.5, tot=55.5,
  rec="SHSU 1-2, TTU 3-0", ana="34.5-point mismatch. Implied Texas Tech team total ~45. A team up 30 at half stops scoring; that is where the value lives, not in laying 34.5.",
  bet="Texas Tech 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="Starters playing the 4th quarter"),
dict(id=7, div="FBS", et="12:00", a="Bucknell (FCS)", h="Pittsburgh", sp=-53.5, tot=63.5, fcsopp=True,
  rec="PITT 3-0, BUCK 1-3", ana="FBS-vs-FCS money game. Implied Pitt team total 58.5 - that is a first-half number being priced as a full game. Backups play the second half.",
  bet="Pitt 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="Pitt keeping starters in"),
dict(id=8, div="FBS", et="12:45", a="South Alabama", h="Kentucky", sp=-20.0, tot=54.5, rec="both 2-1",
  ana="No independent model retrieved. 20 points is a big number for an SEC team with a 2-1 record against a competent Sun Belt side, but there is no data to lean on.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=9, div="FBS", et="14:00", a="Notre Dame", h="Purdue", sp=27.5, tot=58.5, mlh=1600, mla=-7000,
  sp_h=15, sp_a=41, other="SP+: ND by 26.3, 95%",
  ana="SP+ has Notre Dame by 26.3 - within 1.2 of the market. Total SP+ 56 vs 58.5 is a mild under. Nothing actionable at -7000.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=10, div="FBS", et="14:00", a="Northern Illinois", h="Georgia State", sp=-10.0, tot=56.5, mlh=-417, mla=300,
  ana="No model retrieved. Georgia State a 10-point home favourite in Atlanta. No read.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=11, div="FBS", et="15:30", a="Ole Miss", h="Florida", sp=-3.5, tot=58.5, mlh=-164, mla=136, to=-115, tu=-105, sph=-102, spa=-120,
  fpi_h=0.532, other="ESPN betting analysts list Ole Miss among Week 4 plays", wx="Sunny, 82F, 2% precip", wxc="clear",
  ana="The one game where FPI breaks its own pattern: FPI is MORE bullish than the market on nearly every favourite today, yet here it gives Florida only 53.2% (about a 1.3-pt favourite) against a market of -3.5. That is a residual against FPI's own bias, which makes it more meaningful than a raw gap. ESPN's betting desk is on Ole Miss too.",
  bet="Ole Miss +3.5", btype="Model", stake="1", conf="Low-Med", kill="Line moving to Ole Miss +2.5 (value gone) or Florida QB news"),
dict(id=12, div="FBS", et="15:30", a="Utah", h="Iowa State", sp=8.0, tot=48.5, mla=-350,
  sp_h=20, sp_a=29, other="numberFire: Utah 75.2%", wxc="rain",
  wx="STEADY RAIN morning, showers continuing through the afternoon, 64F, SE 5-10",
  rec="UTAH 3-0 (#15), ISU 2-1", line="FanDuel 47.5 (o-114/u-106); most books 48.5",
  ana="SP+ 29-20 (+9, total 49) agrees with the side and the total - but SP+ does not know it is raining. Kickoff sits inside the rain window. Books disagree 47.5 vs 48.5, so the under has a free point attached.",
  bet="UNDER 48.5 (not 47.5)", btype="Weather+Shop", stake="1", conf="Low-Med",
  kill="Rain clearing before 15:30 ET, or 48.5 gone", evcalc=dict(side="under", line=48.5, price=-110, base=49.0, adj=(-1,-2,-3))),
dict(id=13, div="FBS", et="15:30", a="Iowa", h="Michigan", sp=-5.5, tot=38.5, mlh=-218, mla=180,
  fpi_h=0.651, sp_h=23.2, sp_a=22.9, wx="Sunny, 72F, NNE 5-10, 12% rain", wxc="clear",
  rec="MICH FPI #20, IOWA FPI #28",
  ana="SP+ calls it a coin flip (Michigan by 0.3, 51%) while FPI (65.1%) matches the market. Models split on the side. The total is the story: 38.5 is the lowest on the board, SP+ projects 46.1, and there is no weather to explain the gap - Ann Arbor is sunny with light wind. Iowa unders are a well-known market habit, which is exactly why the number may be shaded too far.",
  bet="Lean OVER 38.5", btype="Model", stake="0.5", conf="Low", kill="Either offence's starting QB out"),
dict(id=14, div="FBS", et="15:30", a="Oklahoma", h="Georgia", sp=-13.5, tot=44.5,
  fpi_h=0.834, sp_h=31, sp_a=18, other="SportsLine model backs Oklahoma +13.5/+14",
  rec="UGA #2, OU #24",
  ana="SP+ (Georgia by 13) equals the market; FPI (83.4%) is higher; SportsLine is on Oklahoma. No consensus on the side. SP+ total 49 vs 44.5 leans over, but a one-model total gap is weak evidence.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=15, div="FBS", et="15:30", a="TCU", h="UCF", sp=3.0, tot=48.5, mla=-156, other="dimers model: TCU 57%",
  inj="UCF QB Alonza Barnett III OUT (hamstring; ruled out 9/20). Keyone Jenkins starts again. TCU WR Jordan Dwyer back.",
  rec="both 2-1", ana="The UCF quarterback change is a week old and Jenkins already started last week - it is fully in TCU -3. dimers (57%) is close to the market (61%). Nothing left in the number.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=16, div="FBS", et="15:30", a="William & Mary (FCS)", h="Duke", sp=-43.5, tot=62.5, fcsopp=True,
  ana="Money game. Implied Duke team total 53.0. Second-half bench time is not priced.", bet="Duke 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="Duke starters in late"),
dict(id=17, div="FBS", et="15:00", a="Central Arkansas (FCS)", h="Florida State", sp=-45.5, tot=63.5, fcsopp=True,
  ana="Money game. Implied FSU team total 54.5.", bet="FSU 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="FSU starters in late"),
dict(id=18, div="FBS", et="15:30", a="New Mexico", h="New Mexico State", sp=11.5, tot=48.5, mlh=340, mla=-450, to=-115, tu=-105,
  line="UNM -11.5 to -13.5 across books; totals 48.5-50.5",
  ana="Two full points of disagreement on both the spread and the total. That is the entire opportunity - no model retrieved.",
  bet="Shop: NMSU +13.5 or UNM -11.5; over 48.5 / under 50.5", btype="Shop", stake="0.5", conf="Low", kill="Books converging"),
dict(id=19, div="FBS", et="15:00", a="Hawaii", h="Wyoming", sp=3.5, tot=43.5, mlh=118, mla=-142, to=-114, tu=-106,
  wx="Mostly sunny, 74F, WSW 10-20 mph (17 mph cited)", wxc="wind", rec="both 1-2",
  ana="Hawaii is a road favourite at the highest stadium in Division I. The venue engine prices Wyoming's home field at +4.5 (crowd 3.0 + altitude 1.5) against the flat 2.5 most public models use - two points the market may be under-weighting. Altitude is a fourth-quarter effect, so a sea-level Hawaii team fading late favours Wyoming second-half and live.",
  bet="Lean Wyoming +3.5; better: Wyoming 2H / live", btype="Situational", stake="0.5", conf="Low", kill="Hawaii leading big at half"),
dict(id=20, div="FBS", et="16:15", a="Vanderbilt", h="Auburn", sp=-9.5, tot=54.5, mlh=-365, mla=285, fpi_h=0.751,
  ana="FPI 74.9-75.3% sits right on the market. No disagreement, no bet.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=21, div="FBS", et="17:00", a="Wisconsin", h="Penn State", sp=-9.5, tot=44.5, mlh=-375, mla=310, to=-110, tu=-110, sph=-115, spa=-108,
  fpi_h=0.876, sp_h=32, sp_a=15, other="SP+: PSU by 16.5, 85%", wxc="wind",
  wx="Mostly sunny 69-73F, N 10-20 mph gusting ~25",
  inj="No QB injuries (PSU Becht healthy). WIS OUT: CB Cai Bates, WR Jaylon Domingeaux, OL Michael Roeske, DL Xavier Ukponu; Q: RB Abu Sama III, WR Malachi Coleman. PSU OUT: CBs Joshua Johnson, Tyler Armstead, TE Cooper Alexander, OL Will Tompkins.",
  ana="Both independent models land on the same side, far from the market: SP+ Penn State by 16.5, FPI 87.6% (about 19). Market -9.5. The injury report does not explain a 7-9 point gap. The most likely explanation is that week-4 models still carry heavy preseason weight while the market has adjusted to what Penn State has shown. Two-model consensus is real signal, but a gap this big is also a warning.",
  bet="Penn State -9.5", btype="Model", stake="1", conf="Low-Med", kill="PSU CB depth being exploited early; Wisconsin's questionable RBs all active"),
dict(id=22, div="FBS", et="18:00", a="Delaware", h="Virginia", sp=-19.5, tot=52.5,
  ana="No model retrieved. Virginia 19.5 over a second-year FBS program.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=23, div="FBS", et="18:00", a="James Madison", h="Old Dominion", sp=6.5, tot=44.5, mlh=190, mla=-235,
  rec="JMU 3-0, ODU 1-2", line="Spread 5.5-6.5, total 44.5-45.5",
  ana="A full point of disagreement on both markets. No model.", bet="Shop: ODU +6.5 or JMU -5.5", btype="Shop", stake="0.5", conf="Low", kill="-"),
dict(id=24, div="FBS", et="18:30", a="Central Michigan", h="Miami (FL)", sp=-41.5, tot=53.5, to=-115, tu=-105, sph=-114, spa=-106,
  ana="41.5-point spread. Implied Miami team total 47.5 on a night the backups will play the second half.", bet="Miami 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="-"),
dict(id=25, div="FBS", et="19:00", a="Kansas State", h="Cincinnati", sp=6.5, tot=55.5, to=-105, tu=-109, spa=-105, sph=-108,
  fpi_h=0.413, other="ESPN Matchup Predictor KSU 58.7% (current). dimers: KSU 30-26. SP+ rank KSU 24th, CIN 42nd. NOTE: a 44.3% KSU figure in search results came from a PRESEASON forecast and was discarded.",
  rec="both 3-0", ana="Two current models (ESPN Matchup Predictor 58.7%, dimers 30-26) both put Kansas State ahead by ~4, short of the 6.5 on the road. This is the tightest-held market on the board (3.05%), meaning sharp money has already been through it - the least likely place for a real edge.",
  bet="Lean Cincinnati +6.5", btype="Model", stake="0.5", conf="Low", kill="Line moving to +5.5"),
dict(id=26, div="FBS", et="19:00", a="Oklahoma State", h="West Virginia", sp=-2.0, tot=61.5, mlh=-126, mla=104,
  fpi_h=0.597, sp_h=28, sp_a=26, wx="Partly cloudy, upper 60s, N 5-10", wxc="clear",
  line="Alt WVU -1.5 / total 59.5", rec="OKST beat Oregon 39-31",
  ana="SP+ projects 28-26 - the side matches the market almost exactly - but a 54 total against 61.5. That 7.5-point total gap is the largest SP+ disagreement on the board with NO weather to explain it. The market is likely pricing Oklahoma State's 70-point game against Oregon; SP+ is pricing the season. Books disagree 59.5 vs 61.5, so if you play the under, 61.5 is worth two free points.",
  bet="UNDER 61.5 (not 59.5)", btype="Model+Shop", stake="1", conf="Low-Med", kill="Early explosive plays confirming the shootout profile"),
dict(id=27, div="FBS", et="19:00", a="Southern Miss", h="Tulane", sp=-18.5, tot=52.5, rec="both 1-2",
  ana="No model. Note: venue DB lists Tulane at the Superdome; retrieved data says Yulman Stadium (outdoors) - DB may be stale, no HFA used.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=28, div="FBS", et="19:30", a="Texas A&M", h="LSU", sp=-9.5, tot=52.5,
  fpi_h=0.628, sp_h=27, sp_a=23, wx="Partly cloudy, 66F, light/variable, 7% precip", wxc="clear",
  line="Opened A&M +10.5; now +9.5 (some -8 at -120). Totals 52-53.5.",
  rec="A&M lost in week 3. Under Elko/Reed, A&M is 2-0 vs LSU: 38-23 (2024), 49-25 IN BATON ROUGE (2025).",
  ana="The strongest side on the board by this method: BOTH independent models disagree with the market in the same direction. SP+ projects LSU 27-23 (by 4); FPI gives LSU 62.8% (about 5.4). Market: 9.5. The line has already moved a point toward A&M, and A&M has beaten LSU twice running under this staff, including by 24 in Death Valley. Three separate signals, one direction.",
  bet="Texas A&M +9.5", btype="Model", stake="1", conf="Medium", kill="A&M +8 or worse (value gone), or Marcel Reed not starting"),
dict(id=29, div="FBS", et="19:30", a="Oregon", h="USC", sp=3.5, tot=61.5, mlh=140, mla=-170, to=-110, tu=-110, spa=-106, sph=-114,
  sp_h=29, sp_a=30, other="SportsLine computer model likes USC. SP+ ranks ORE 5th, USC 8th (AP 20 / 12).",
  line="Spread ranges ORE -1.5 to -3.5 across books", rec="USC 4-0; ORE lost 39-31 at OKST",
  ana="SP+ projects 30-29 Oregon - a one-point game - and SportsLine independently likes USC. Two models against a 3.5-point number. Critically, the market itself disagrees by two full points across books: +3.5 on USC is worth materially more than +1.5.",
  bet="USC +3.5 (NOT +1.5)", btype="Model+Shop", stake="1", conf="Low-Med", kill="Only +1.5/+2.5 available"),
dict(id=30, div="FBS", et="19:30", a="Appalachian State", h="NC State", sp=-14.0, tot=55.5, mlh=-671, mla=470, line="Alt -13.5",
  ana="No model. Half-point of shopping only.", bet="Shop: App State +14", btype="Shop", stake="0.5", conf="Low", kill="-"),
dict(id=31, div="FBS", et="19:30", a="Troy", h="Utah State", sp=-3.0, tot=47.5, mlh=-152, mla=126,
  ana="Venue engine: Utah State home field 3.8 (crowd 2.8 + altitude 1.0 vs sea-level Troy) against a flat 2.5 - about 1.3 points the market may not fully carry. Thin, altitude weights to the second half.",
  bet="Lean Utah State 2H", btype="Situational", stake="0.5", conf="Low", kill="-"),
dict(id=32, div="FBS", et="19:30", a="Arizona", h="Washington State", sp=10.5, tot=48.5, mlh=340, mla=-450, to=-110, tu=-110,
  line="Spread 9.5-10.5, total 47.5-48.5", ana="A point of disagreement on both markets. No model.",
  bet="Shop: WSU +10.5 or ARIZ -9.5", btype="Shop", stake="0.5", conf="Low", kill="-"),
dict(id=33, div="FBS", et="20:00", a="Tulsa", h="Arkansas", sp=-7.0, tot=50.5, mlh=-275, mla=220,
  ana="No model retrieved. Arkansas -7 on a key number.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=34, div="FBS", et="19:45", a="Missouri", h="Mississippi State", sp=-6.5, tot=58.5, mlh=-215, mla=176, to=-118, tu=-104,
  fpi_h=0.673, sp_h=26.6, sp_a=27.1, other="ESPN betting analysts list Missouri among Week 4 plays",
  ana="SP+ has Missouri winning OUTRIGHT (27.1-26.6) while FPI (67.3%, ~7.4) matches the market. Split on the side, so no side bet. The total is cleaner: SP+ 53.7 vs 58.5 - nearly five points - and the under is the cheaper side at -104.",
  bet="UNDER 58.5 (-104)", btype="Model", stake="0.5", conf="Low", kill="Pace tells early"),
dict(id=35, div="FBS", et="night", a="South Carolina", h="Alabama", sp=-12.5, tot=54.5, mlh=-521, mla=385, to=-106, tu=-114,
  fpi_h=0.822, sp_h=30, sp_a=21,
  ana="SP+ Alabama by 9; FPI 82.2% (~15). Market 12.5 sits between them - split. SP+ total 51 vs 54.5 leans under, but the under is the expensive side (-114).",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=36, div="FBS", et="21:00", a="Missouri State", h="SMU", sp=-34.5, tot=59.5, fcsopp=True, rec="SMU #22 2-1, MOST 1-2",
  ana="34.5-point mismatch; implied SMU team total 47.0.", bet="SMU 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="-"),
dict(id=37, div="FBS", et="21:00", a="Oregon State", h="UTEP", sp=10.5, tot=55.5, rec="both 1-2",
  ana="No model. Road favourite by 10.5 between two 1-2 teams.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=38, div="FBS", et="19:00", a="Louisiana", h="Charlotte", sp=10.0, tot=49.5, mlh=322, mla=-431,
  line="Spread 10-10.5, totals 48.5-50.5", ana="Two points of total disagreement.", bet="Shop: over 48.5 / under 50.5; CLT +10.5", btype="Shop", stake="0.5", conf="Low", kill="-"),
dict(id=39, div="FBS", et="22:30", a="Air Force", h="Nevada", sp=5.5, tot=50.5,
  ana="Air Force trains at 6,621 ft, so Reno's 4,600 ft gives Nevada NO altitude edge (negative differential). Flat home field only.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=40, div="FBS", et="22:30", a="Georgia Tech", h="Stanford", sp=3.5, tot=48.5, mlh=140, mla=-170, to=-105, tu=-115, sph=-110, spa=-110,
  fpi_h=0.325, other="SP+ favours GT (score not retrieved). FPI was 57% GT last week, now 67.5% after GT beat Mercer and Stanford lost to Duke.",
  ana="FPI makes Georgia Tech 67.5% (~7.5) against -3.5 - but FPI runs hot on favourites all day, so this is mostly its bias, not an edge.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
# ------------------------------------------------------------------ FCS
dict(id=101, div="FCS", conf_="MVFC", et="13:00", a="North Dakota", h="Indiana State", sp=16.5, tot=58.5, mlh=710, mla=-1320, to=-104, tu=-119,
  ana="UND a 16.5-pt road favourite. No FCS model retrievable (FPI does not cover FCS).", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=102, div="FCS", conf_="SoCon", et="14:00", a="Chattanooga", h="The Citadel", sp=11.5, tot=47.5, mlh=286, mla=-385, to=-104, tu=-111,
  line="CHAT -11.5 (-111) at one book, CIT +10.5 (-132) at another",
  ana="Two books on different numbers - a full point available on whichever side you want.", bet="Shop: Citadel +11.5 or Chattanooga -10.5", btype="Shop", stake="0.5", conf="Low-Med", kill="Books converging to 11"),
dict(id=103, div="FCS", conf_="SoCon/CAA", et="14:00", a="Furman", h="Richmond", sp=-3.0, tot=44.5, mlh=-152, mla=122,
  rec="FUR 2-2, RICH 3-1 (2-0 home)", ana="Richmond -3 on the key number. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=104, div="FCS", conf_="Patriot/CAA", et="14:30", a="Colgate", h="Villanova", sp=-10.5, tot=49.5, wxc="storm_edge",
  wx="Philadelphia: Nor'easter - sustained 15-25 mph, gusts to 45, rain bands from midday",
  ana="Played at the western edge of the Nor'easter. Sustained 15-25 with 45-mph gusts is above the passing/kicking threshold. No sign in the market that the total has moved for it.",
  bet="Lean UNDER 49.5", btype="Weather", stake="0.5", conf="Low-Med", kill="Wind under 15 at kick",
  evcalc=dict(side="under", line=49.5, price=-110, base=49.5, adj=(-2,-4,-6))),
dict(id=105, div="FCS", conf_="Big Sky", et="16:00", a="Montana", h="UC Davis", sp=-2.5, tot=None,
  ana="Total not retrievable. Montana travels DOWN in elevation (3,200 ft to ~50 ft) - no altitude effect.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=106, div="FCS", conf_="MVFC", et="16:00", a="Illinois State", h="Northern Iowa", sp=19.5, tot=58.5, mlh=700, mla=-1280, wxc="indoor",
  wx="UNI-Dome - indoor", ana="Indoors, so weather is a non-factor. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=107, div="FCS", conf_="MVFC", et="16:00", a="Southern Illinois", h="Murray State", sp=16.5, tot=53.5, mlh=505, mla=-790, to=-111, tu=-111,
  rec="SIU 2-2, MUR 1-3", ana="No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=108, div="FCS", conf_="CAA", et="16:00", a="Maine", h="Elon", sp=-5.5, tot=44.5, mlh=-209, mla=165, to=-111, tu=-111,
  wx="Elon, NC - outside the storm core", wxc="clear", ana="No model. Maine lost to BC only 22-16 two weeks ago.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=109, div="FCS", conf_="CAA/Patriot", et="17:00", a="Stony Brook", h="Fordham", sp=10.5, tot=52.5, mlh=313, mla=-429, to=-144, tu=116, wxc="storm_core",
  wx="BRONX NOR'EASTER: N 20-30 mph, gusts 45-55, 90% rain, 1-2 in; wind advisory through Sunday; coastal flood warning",
  ana="The best bet on the board. The game is played in the middle of a Nor'easter - sustained winds of 20-30 with gusts to 55 and a 90% chance of heavy rain - yet the market has the OVER as a heavy -144 favourite. That is the opposite of what a storm game should look like, and it is what an FCS market that has not priced the weather looks like. The under is PLUS money. Even on conservative storm assumptions it clears the EV floor comfortably.",
  bet="UNDER 52.5 (+116)", btype="Weather", stake="1", conf="Medium-High", kill="Storm stalling offshore / winds under 15 at kick; the number dropping to 49",
  evcalc=dict(side="under", line=52.5, price=116, base=None, adj=(-3,-6,-9))),
dict(id=110, div="FCS", conf_="MVFC", et="18:00", a="South Dakota", h="Youngstown State", sp=-1.5, tot=65.5,
  ana="Highest total of the entire day, FBS or FCS, on a near pick'em. No model to challenge 65.5.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=111, div="FCS", conf_="SWAC", et="18:00", a="Southern", h="Jackson State", sp=-20.5, tot=57.5, mlh=-1200, mla=670,
  rec="JSU 3-0 at home; SOU 2-2 away. Series 36-36, JSU has won 7 straight.", ana="No model. JSU opens SWAC play at home.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=112, div="FCS", conf_="SoCon", et="18:00", a="Western Carolina", h="East Tennessee St", sp=-1.5, tot=63.5, mlh=-128, mla=103, to=-116, tu=-107,
  rec="both 2-2", ana="Second-highest FCS total. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=113, div="FCS", conf_="Big Sky", et="15:00", a="Northern Arizona", h="Montana State", sp=-20.5, tot=56.5, mlh=-1724, mla=783,
  ana="CORRECTION CASE: the venue engine first credited Montana State with +1.0 of altitude by defaulting NAU to sea level. NAU plays in Flagstaff at ~6,900 ft - higher than Bozeman. True altitude edge: zero. Do not add it.",
  bet="No bet (do NOT add altitude for MSU)", btype="Situational", stake="0", conf="Medium", kill="-"),
dict(id=114, div="FCS", conf_="Patriot/Ivy", et="13:00", a="Lehigh", h="Penn", sp=-10.5, tot=48.5, mlh=310, wxc="storm_edge",
  wx="Franklin Field, Philadelphia: Nor'easter - sustained 15-25 mph, gusts to 45, rain bands by midday",
  ana="Same storm-edge conditions as Villanova. Lehigh is a top-10 FCS team; Penn is non-scholarship Ivy. Wind this strong compresses both offences.",
  bet="Lean UNDER 48.5", btype="Weather", stake="0.5", conf="Low-Med", kill="Wind under 15 at kick",
  evcalc=dict(side="under", line=48.5, price=-110, base=48.5, adj=(-2,-4,-6))),
dict(id=115, div="FCS", conf_="CAA/NEC", et="16:00", a="New Hampshire", h="Sacred Heart", sp=-4.0, tot=44.5, mlh=-163, mla=130, wxc="storm_core",
  wx="Fairfield, CT: wind advisory; gusts 40-55 inland, 50-60 shoreline; 1-3 in rain",
  ana="Core-storm conditions in coastal Connecticut. But 44.5 is already a low FCS number, so some of the weather may be in it. Strong conditions, less certain mispricing than Fordham.",
  bet="Lean UNDER 44.5", btype="Weather", stake="0.5", conf="Low", kill="Number already moved down from a higher open",
  evcalc=dict(side="under", line=44.5, price=-110, base=44.5, adj=(-2,-4,-6))),
dict(id=116, div="FCS", conf_="CAA/Ivy", et="15:00", a="UAlbany", h="Princeton", sp=1.5, tot=43.5, wxc="storm_edge",
  wx="Princeton NJ: N 15-25 mph, gusts 40, 90% rain",
  ana="Storm-edge conditions on an already-low total. Princeton is non-scholarship Ivy against scholarship UAlbany - UAlbany only -1.5 is a small number for that gap.",
  bet="No bet (total already low; lean UAlbany)", btype="None", stake="0", conf="Low", kill="-"),
dict(id=117, div="FCS", conf_="MAAC/Ivy", et="13:00", a="Monmouth", h="Dartmouth", sp=-2.5, tot=51.5, wxc="rain",
  wx="Hanover NH: NNE 5-10 mph, rain likely after 2pm - OUTSIDE the storm core",
  line="DART -2.5 at one book, MON +3 at another",
  ana="Not a storm game - Hanover sits outside the Nor'easter's core with light wind. The value is the half-point to +3.", bet="Shop: Monmouth +3", btype="Shop", stake="0.5", conf="Low", kill="-"),
dict(id=118, div="FCS", conf_="Big South/Patriot", et="16:00", a="Presbyterian", h="Marist", sp=-8.5, tot=45.5, to=-115, tu=-115, wxc="storm_edge",
  wx="Poughkeepsie NY - named in storm-impact reports; not independently verified", line="Total 45 / 45.5",
  ana="VSiN lists this among storm-affected games, but I could not verify Poughkeepsie's specific forecast. Lower confidence than the verified storm games.",
  bet="Lean UNDER 45.5", btype="Weather", stake="0.25", conf="Low", kill="Local forecast showing light wind"),
dict(id=119, div="FCS", conf_="Ivy", et="13:00", a="Yale", h="Cornell", sp=15.5, tot=47.5, mlh=333, mla=-461,
  line="YALE -15.5 at one book, CORNELL +14 at another",
  ana="A 1.5-point spread disagreement - the largest shop on the FCS board. Ithaca sits outside the storm core.", bet="Shop: Cornell +15.5 or Yale -14", btype="Shop", stake="0.5", conf="Low-Med", kill="-"),
]

# ------------------------------------------------------------------ FBS added on the second sweep
G += [
dict(id=41, div="FBS", et="12:00", a="Colorado State", h="UTSA", sp=-13.5, tot=57.5, mlh=-581, mla=420, to=-118, tu=-104,
  ana="No model retrieved. UTSA -13.5 at home over a Colorado State team in its first Pac-12 season. The under is the cheaper side of the total (-104).",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=42, div="FBS", et="16:05", a="Houston", h="Georgia Southern", sp=17.5, tot=56.5, mlh=680, mla=-1111,
  ana="Big 12 Houston a 17.5-pt road favourite at Paulson Stadium. No model. (An early search wrongly listed this as Houston CHRISTIAN - it is the FBS Houston.)",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=43, div="FBS", et="15:30", a="Boise State", h="Western Michigan", sp=7.5, tot=48.5, mlh=235, mla=-290,
  line="Totals 48.5 / 49.5 / 50.5 across books", ana="Two full points of disagreement on the total. No model - the number is the only edge.",
  bet="Shop: over 48.5 or under 50.5", btype="Shop", stake="0.5", conf="Low", kill="-"),
dict(id=44, div="FBS", et="15:30", a="San Diego State", h="Toledo", sp=-2.5, tot=51.5, mlh=-146, mla=122, to=-105, tu=-115, sph=-122, spa=100,
  ana="Toledo -2.5 is juiced to -122; SDSU +2.5 at even money devigs to about 47.6% - still negative EV. No model.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=45, div="FBS", et="17:00", a="South Florida", h="Bowling Green", sp=17.5, tot=48.5, mlh=640, mla=-1000, to=-110, tu=-110, sph=-110, spa=-110,
  ana="USF a 17.5-pt road favourite. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=46, div="FBS", et="15:30", a="UConn", h="Miami (OH)", sp=-3.5, tot=51.5, mlh=-175, mla=145, to=-115, tu=-105, sph=-102, spa=-118,
  rec="UConn 2-1, Miami (OH) 1-2", ana="No model. A 2-1 team getting 3.5 against a 1-2 team - the record gap is the market's own information.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=47, div="FBS", et="15:30", a="Ball State", h="Kent State", sp=-2.5, tot=None,
  ana="Kent State -2.5. Total not retrievable.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=48, div="FBS", et="19:00", a="Middle Tennessee", h="Jacksonville State", sp=-7.5, tot=51.5, mlh=-280, mla=225, to=-110, tu=-110, sph=-104, spa=-118,
  ana="No model. Jax State -7.5 in its C-USA opener.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=49, div="FBS", et="21:00", a="UMass", h="Sacramento State", sp=4.5, tot=48.5,
  ana="Sac State in its first FBS season (MAC affiliate). UMass a 4.5-pt road favourite. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=50, div="FBS", et="15:30", a="Nebraska", h="Michigan State", sp=5.5, tot=48.5, mlh=188, mla=-230, sph=-102, spa=-120,
  ana="Nebraska -5.5 is juiced to -120; Michigan State +5.5 at -102 is the cheaper side. No model to lean on.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=51, div="FBS", et="13:30", a="UCLA", h="Maryland", sp=1.5, tot=56.5, mlh=104, mla=-125,
  ana="UCLA a 1.5-pt road favourite in College Park. Maryland sits at the edge of the Nor'easter's mid-Atlantic reach - forecast not verified, so no weather adjustment applied.",
  bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=52, div="FBS", et="23:00", a="Minnesota", h="Washington", sp=-9.5, tot=45.5,
  ana="Washington -9.5 at Husky Stadium, late kick. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=53, div="FBS", et="22:00", a="Rice", h="Fresno State", sp=-13.5, tot=44.5,
  ana="Fresno State -13.5 in its first Pac-12 season. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=54, div="FBS", et="12:00", a="UNLV", h="Akron", sp=13.5, tot=49.5,
  ana="UNLV a 13.5-pt road favourite. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=55, div="FBS", et="19:00", a="Kennesaw State", h="Arkansas State", sp=-6.5, tot=52.5,
  ana="Arkansas State -6.5. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=56, div="FBS", et="20:00", a="Florida Atlantic", h="ULM", sp=13.5, tot=57.5,
  ana="FAU a 13.5-pt road favourite. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=57, div="FBS", et="15:30", a="Liberty", h="Coastal Carolina", sp=2.5, tot=50.5,
  ana="Liberty a 2.5-pt road favourite. No model.", bet="No bet", btype="None", stake="0", conf="Low", kill="-"),
dict(id=58, div="FBS", et="17:00", a="Incarnate Word (FCS)", h="Texas State", sp=-30.5, tot=61.5, fcsopp=True,
  ana="UIW is one of the better FCS offences, which is why the total is 61.5. Implied Texas State team total 46.0; bench time late.",
  bet="Texas State 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="-"),
dict(id=59, div="FBS", et="18:30", a="Houston Christian (FCS)", h="North Texas", sp=-37.5, tot=None, fcsopp=True,
  ana="Money game, North Texas -37.5. Total not retrievable.", bet="North Texas 2H under", btype="Structural", stake="0.5", conf="Low", kill="-"),
dict(id=60, div="FBS", et="13:00", a="Lindenwood (FCS)", h="Eastern Michigan", sp=-26.5, tot=49.5, fcsopp=True,
  ana="Money game. Implied EMU team total 38.0.", bet="EMU 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="-"),
dict(id=61, div="FBS", et="15:30", a="Robert Morris (FCS)", h="Buffalo", sp=-28.5, tot=44.5, fcsopp=True,
  ana="Money game. Implied Buffalo team total 36.5.", bet="Buffalo 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="-"),
dict(id=62, div="FBS", et="15:30", a="Stonehill (FCS)", h="Ohio", sp=-37.5, tot=51.5, fcsopp=True,
  ana="Money game. Implied Ohio team total 44.5.", bet="Ohio 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="-"),
dict(id=63, div="FBS", et="16:00", a="NC Central (FCS)", h="East Carolina", sp=-31.5, tot=52.5, fcsopp=True,
  ana="Money game. NCCU is a strong MEAC side. Implied ECU team total 42.0.", bet="ECU 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="-"),
dict(id=64, div="FBS", et="18:00", a="LIU (FCS)", h="FIU", sp=-34.5, tot=51.5, fcsopp=True,
  ana="Money game. Implied FIU team total 43.0.", bet="FIU 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="-"),
dict(id=65, div="FBS", et="19:00", a="Mercyhurst (FCS)", h="Western Kentucky", sp=-37.5, tot=54.5, fcsopp=True,
  ana="Money game. Implied WKU team total 46.0.", bet="WKU 2H under / team-total under", btype="Structural", stake="0.5", conf="Low", kill="-"),
# ------------------------------------------------------------------ FCS added on the second sweep
dict(id=120, div="FCS", conf_="Big Sky", et="16:00", a="Cal Poly", h="Eastern Washington", sp=-3.0, tot=None,
  line="EWU -3 at one book, Cal Poly +3.5 at another", ana="Half-point across the key number of 3. Total not retrievable.",
  bet="Shop: Cal Poly +3.5", btype="Shop", stake="0.5", conf="Low", kill="-"),
dict(id=121, div="FCS", conf_="MVFC", et="15:00", a="Eastern Illinois", h="South Dakota State", sp=-34.5, tot=53.5,
  ana="FCS power SDSU closes non-conference play. At -34.5 the starters sit early. Implied SDSU team total 44.0.",
  bet="SDSU 2H under / team-total under", btype="Structural", stake="0.25", conf="Low", kill="-"),
]

NO_MARKET = [
 ("FBS","Gardner-Webb (FCS)","Marshall", "No posted line at the books searched. A power-rating model projects Marshall -11.7; prediction market ~88% Marshall."),
 ("FCS","Idaho State","Southern Utah", ""), ("FCS","Portland State","Weber State", ""),
 ("FCS","Utah Tech","Northern Colorado", ""), ("FCS","East Texas A&M","McNeese", ""), ("FCS","Lamar","Nicholls", ""),
 ("FCS","Southeastern Louisiana","Northwestern State", ""), ("FCS","Texas Southern","Alcorn State", "dimers publishes a model pick; no book line found"),
 ("FCS","Holy Cross","Lafayette", ""), ("FCS","Columbia","Georgetown", ""), ("FCS","Campbell","Hampton", ""),
 ("FCS","VMI","Samford", "dimers lists a best bet on this game; no book line found"), ("FCS","Tennessee Tech","Wofford", ""),
 ("FCS","New Haven","Merrimack", "NOR'EASTER - North Andover MA. Would be a storm-under candidate if a line surfaces."),
 ("FCS","Rhode Island","North Carolina A&T", ""), ("FCS","UT Martin","Austin Peay", ""), ("FCS","Western Illinois","North Alabama", ""),
 ("FCS","Towson","Delaware State", ""), ("FCS","Norfolk State","Chicago State", ""),
 ("FCS","Butler","Valparaiso", "Pioneer League (non-scholarship)"), ("FCS","Drake","Davidson", "Pioneer League (non-scholarship)"),
 ("FCS","San Diego","St. Thomas", "Pioneer League (non-scholarship)"),
]
